config/routes.rb
Bobs::Application.routes.draw do
	
  resources :expenses

	get 'stats' => "admin#index"
	
	get 'login' => "sessions#new"
	post 'login' => "sessions#create"
	get 'logout' => "sessions#destroy"
  
	
  resources :users

  get "time/set"
  get "time/set_today"
  get "time/increase"
  get "time/decrease"

  resources :bookings

  resources :guests
	
  resources :beds

  root 'beds#index'

  get 'total' => 'beds#total'

  

end

app/models/bed.rb
class Bed < ActiveRecord::Base
	has_many :bookings, dependent: :destroy
  has_many :guests, through: :bookings
end

app/controllers/beds_controller.rb
class BedsController < ApplicationController
  before_action :set_bed, only: [:show, :edit, :update, :destroy]
	before_filter :authorize_admin, only: [:create, :new]
  
  # GET /beds
  # GET /beds.json
  def index
    @beds = Bed.all
  end
  
  def total
    @beds = Bed.all
  end

  # GET /beds/1
  # GET /beds/1.json
  def show
  end

  # GET /beds/new
  def new
    @bed = Bed.new
  end

  # GET /beds/1/edit
  def edit
  end

  # POST /beds
  # POST /beds.json
  def create
    @bed = Bed.new(bed_params)

    respond_to do |format|
      if @bed.save
        format.html { redirect_to @bed, notice: 'Bed was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bed }
      else
        format.html { render action: 'new' }
        format.json { render json: @bed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beds/1
  # PATCH/PUT /beds/1.json
  def update
    respond_to do |format|
      if @bed.update(bed_params)
        format.html { redirect_to @bed, notice: 'Bed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beds/1
  # DELETE /beds/1.json
  def destroy
    @bed.destroy
    respond_to do |format|
      format.html { redirect_to beds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bed
      @bed = Bed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bed_params
      params.require(:bed).permit(:room, :number)
    end
end

app/helpers/beds_helper.rb
module BedsHelper
end

app/views/beds/_count_Total.html.erb
<% @total_price = 0 %>
<% total_deposit = 0 %>
<% @total_credit_card = 0 %>
<% @total_cash = 0 %>

<% @beds.each do |bed| %>
	
	<% if bed.room == room_variable_total %>	
			
		
		
		<% if defined? shift_variable %>
		
			<% if defined? bed.guests[0].name == "method" and
			bed.bookings[0].check_in_date.strftime("%Y %B %d, %A") == time_variable and
			bed.bookings[0].shift == shift_variable and 
			%>
					
					<!--Check if it's not only a booking but a check in, so the guest payed already the price-->
					<% if bed.bookings[0].status == "Check In" %>
				    <% @total_price += bed.guests[0].price %>
				    <% total_deposit += bed.guests[0].deposit %>
				  
				  
				  <!-- Sum up the credit card payments -->
				  <% if bed.guests[0].payment_method == "Credit Card" %>
				  		<% @total_credit_card += bed.guests[0].price%>
				  <% end %>
				  
				  <!-- Sum up the cash payments -->
				  <% if bed.guests[0].payment_method == "Cash" %>
				  		<% @total_cash += bed.guests[0].price%>
				  <% end %>
					<% end %>
		  <% end %>
		
		<!-- This part is to calculate the day totals-->
		<% else %>
			
				<% if defined? bed.guests[0].name == "method" and
				bed.bookings[0].check_in_date.strftime("%Y %B %d, %A") == time_variable
				%>
					<!--Check if it's not only a booking but a check in, so the guest payed already the price-->
					<% if bed.bookings[0].status == "Check In" %>
				    <% @total_price += bed.guests[0].price %>
				    <% total_deposit += bed.guests[0].deposit %>
					
					
					<!-- Sum up the credit card payments -->
				  <% if bed.guests[0].payment_method == "Credit Card" %>
				  		<% @total_credit_card += bed.guests[0].price%>
				  <% end %>
				  
				  <!-- Sum up the cash payments -->
				  <% if bed.guests[0].payment_method == "Cash" %>
				  		<% @total_cash += bed.guests[0].price%>
				  <% end %>
					<% end %>
					
				<% end %>
		
		<% end %>
	
	<% end %>

<% end %>

<td><%= @total_cash %></td>

<td><%= @total_credit_card %></td>

<td><%= @total_price %></td>

<td><%= total_deposit %></td>

app/views/beds/_form.html.erb
<!DOCTYPE html>

<%= form_for(@bed) do |f| %>
  <% if @bed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bed.errors.count, "error") %> prohibited this bed from being saved:</h2>

      <ul>
      <% @bed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room %><br>
    <%= f.text_field :room %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beds/_room.html.erb
<!DOCTYPE html>

<div class="table-responsive">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Room</th>
      <th>Number</th>
      <th>Name</th>
      <th>Locker</th>
      <th>Nights</th>
      <th>Price</th>
      <th>Deposit</th>
      <th>Payment</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @beds.where(room: room_variable).each do |bed| %>
      <tr>
        <td><%= bed.room %></td>
        <td><%= bed.number %></td>
        
        <!--Check if there are any guests are assigned to the beds
        /if there are not, bed.guests[0].name would be undefined.
        Check guests' booking and check out date, display only those guests that are staying in the hotel during
        the given date.-->
        
        <% if defined? bed.guests[0].name == "method" and
        bed.bookings[0].check_in_date.strftime("%Y%m%d") <= time_variable.to_time.strftime("%Y%m%d") and
        bed.bookings[0].check_out_date.strftime("%Y%m%d") > time_variable.to_time.strftime("%Y%m%d") %>
         
                      <td><%= link_to bed.guests[0].name, edit_guest_path(bed.guests[0]) %></td>
                      
                      <!--Check if guest is checked in yet or is it only a booking and guest still has to check in-->
                      <% if bed.bookings[0].status == "Check In"%>
                                      <td><%= bed.guests[0].locker %></td>
                      <% else %>
                                      <td><%= "Booked" %></td>
                              <% end %>
                              
                      <td>
                      <% if session[:time_variable].present? %>
                      
                                      <% difference = (session[:time_variable].to_date - bed.bookings[0].check_in_date.to_date).to_i %>
                                      <%= nights_left = (bed.bookings[0].check_out_date.to_date -
                                      bed.bookings[0].check_in_date.to_date).to_i - difference %>
                                      
                                      
                      <% else %>
                      
                                      <% difference = (Date.today.to_date - bed.bookings[0].check_in_date.to_date).to_i %>
                                      <%= (bed.bookings[0].check_out_date.to_date - bed.bookings[0].check_in_date.to_date).to_i - difference %>
                                      
                      <% end %>
                      </td>
                      
                      <!--Check if guests are checked in in the given date, if yes, display the price they pay, if not,
                      leave the column empty.-->
                      <% if bed.bookings[0].check_in_date.strftime("%Y %B %d, %A") == time_variable %>
                                    
                                    <!--Check if guest is checked in yet or is it only a booking and guest still has to check in-->
                                    <% if bed.bookings[0].status == "Check In"%>
                                              <td><%= bed.guests[0].price %></td>
                                      <% else %>
                                              <td><%= "Booked" %></td>
                                      <% end %>
                                    
                                  <% else %>
                                    <td>-</td>
                      
                      <% end %>
                      
                                      <!--Check if guest is checked in yet or is it only a booking and guest still has to check in-->
                                    <% if bed.bookings[0].status == "Check In"%>
                                              <td><%= bed.guests[0].deposit %></td>
                                      <% else %>
                                              <td><%= "Booked" %></td>
                                      <% end %>
                                      
                                      <!--Check if guest is checked in yet or is it only a booking and guest still has to check in-->
                                    <% if bed.bookings[0].status == "Check In"%>
                                              <td><%= bed.guests[0].payment_method %></td>
                                      <% else %>
                                              <td><%= "Booked" %></td>
                                      <% end %>
                                      
                                      <td><%= link_to 'Edit Guest', edit_guest_path(bed.guests[0]) %></td>
        <td><%= link_to 'Edit Booking', edit_booking_path(bed.bookings[0]) %></td>
                     
                    <% else %>
                    
                      <td>Room is free</td>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                      <td>-</td>
                       <td><%= link_to '-'%></td>
                       <td><%= link_to '-'%></td>
                      
                     
        
        <% end %>
  				
        <td><%= link_to '', edit_guest_path(bed.guests[0]) %></td>
        <td></td>

        <!-- Don't destroy beds!
        <td><%= link_to 'Destroy', bed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/beds/edit.html.erb
<h1>Editing bed</h1>

<%= render 'form' %>

<%= link_to 'Show', @bed %> |
<%= link_to 'Back', beds_path %>

app/views/beds/index.html.erb
<!DOCTYPE html>

<% if session[:time_variable].present? %>
<% @time_variable = session[:time_variable].strftime("%Y %B %d, %A")%>
<% else %>
<% @time_variable =  Date.today.strftime("%Y %B %d, %A")%>
<% end %>

<ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="#room_A">Room A</a></li>
  <li><a href="#room_B">Room B</a></li>
  <li><a href="#room_C">Room C</a></li>
  <li><a href="#room_DE">Room D & E</a></li>
  <li><a href="#room_F">Room F</a></li>
  <li><a href="#room_G">Room G</a></li>
  <li><a href="#room_H">Room H</a></li>
  <li><a href="#room_L1L2">Room L1 & L2</a></li>
  <li><a href="#room_M1M2">Room M1 & M2</a></li>
  <li><a href="#room_R1R2">Room R1 & R2</a></li>
  <li><a href="#room_Apartments">Apartments</a></li>
</ul>

<div class="tab-content">
	
	<!-- Render the _room page sending the rooms' name as room_variable and the date by as time_variable,
	the rendered page will iterate through the Bed table and display all the guests that are checked in the particular rooms -->
	
  <div class="tab-pane active" id="room_A"><%= render partial: "room", locals: {room_variable: "A",
  time_variable: @time_variable} %></div>
  
  <div class="tab-pane" id="room_B"><%= render partial: "room", locals: {room_variable: "B",
  time_variable: @time_variable} %></div>
  
  <div class="tab-pane" id="room_C"><%= render partial: "room", locals: {room_variable: "C",
  time_variable: @time_variable} %></div>
  
  <div class="tab-pane" id="room_DE"><%= render partial: "room", locals: {room_variable: "D",
  time_variable: @time_variable} %> <br>
  																		<%= render partial: "room", locals: {room_variable: "E",
  time_variable: @time_variable} %></div>
  
  <div class="tab-pane" id="room_F"><%= render partial: "room", locals: {room_variable: "F",
  time_variable: @time_variable} %></div>
  
  <div class="tab-pane" id="room_G"><%= render partial: "room", locals: {room_variable: "G",
  time_variable: @time_variable} %></div>
  
  <div class="tab-pane" id="room_H"><%= render partial: "room", locals: {room_variable: "H",
  time_variable: @time_variable} %></div>
  
  <div class="tab-pane" id="room_L1L2"><%= render partial: "room", locals: {room_variable: "L1",
  time_variable: @time_variable} %> <br>
  																	<%= render partial: "room", locals: {room_variable: "L2",
  time_variable: @time_variable} %></div>
  
  	<div class="tab-pane" id="room_M1M2"><%= render partial: "room", locals: {room_variable: "M1",
  time_variable: @time_variable} %> <br>
  																	<%= render partial: "room", locals: {room_variable: "M2",
  time_variable: @time_variable} %></div>
  
  	<div class="tab-pane" id="room_R1R2"><%= render partial: "room", locals: {room_variable: "R1",
  time_variable: @time_variable} %> <br>
  																	<%= render partial: "room", locals: {room_variable: "R2",
  time_variable: @time_variable} %></div>
	
	<div class="tab-pane" id="room_Apartments"><%= render partial: "room", locals: {room_variable: "Green",
  time_variable: @time_variable} %> <br>
  																	<%= render partial: "room", locals: {room_variable: "Black",
  time_variable: @time_variable} %></div>									
</div>

<br>

<script>
$('#myTab a').click(function (e) {
  e.preventDefault()
  $(this).tab('show')
})
</script>

app/views/beds/new.html.erb
<h1>New bed</h1>

<%= render 'form' %>

<%= link_to 'Back', beds_path %>

app/views/beds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room:</strong>
  <%= @bed.room %>
</p>

<p>
  <strong>Number:</strong>
  <%= @bed.number %>
</p>

<%= link_to 'Edit', edit_bed_path(@bed) %> |
<%= link_to 'Back', beds_path %>

app/views/beds/total.html.erb
<!DOCTYPE html>

<% if session[:time_variable].present? %>
<% @time_variable = session[:time_variable].strftime("%Y %B %d, %A")%>
<% else %>
<% @time_variable =  Date.today.strftime("%Y %B %d, %A")%>
<% end %>

<!--Get the names of the rooms in the array room_names-->

<% room_names = [] unless room_names %>
<% @beds.each do |bed| %>
	<% if room_names.include? bed.room %>
	<% else %>
	<% room_names << bed.room %>
	<% end %>
<% end %>


<!AM Shift>

	<h3>AM Shift</h3>
	<div class="table-responsive">
	<table class="table table-hover">
		<thead>
		  <tr>
		  
		  		<th>Room</th>
		  		<th>Cash</th>
		  		<th>Credit Card</th>
		  		<th>Total</th>
		  		<th>Deposit</th>
		    
		   </tr>
		</thead>
		
	<!--Initialize total revenues to zero. -->
	<% @total_rooms_revenue = 0 %>
	<% @total_credit_card_revenue = 0 %>
	<% @total_cash_revenue = 0 %>
	<% @total_expense = 0 %>

	<!--Iterate through the room names, create variables room_total_ + room name (for example room_total_A, room_total_B etc)
	to store the total revenue for the rooms individually.-->
	<% room_names.each do |name| %>
	
		<tbody>
		<tr>
		<% @i = "room_total_" + name %>
	
		<!--Render the _count_Total page sending the rooms' name as room_variable_total, the rendered page will iterate through the
		Bed table and sum upp all the revenue in the particular rooms.-->
		<td><%= name %> Room</td>
	
		<%= @i = render partial: "count_Total", locals: {room_variable_total: name, time_variable: @time_variable,
		shift_variable: "AM"} %>
	
		<!--Sum up the particular revenues in @total_rooms_revenue variable without deposits-->
		<% @total_rooms_revenue += @total_price %>
		<% @total_credit_card_revenue += @total_credit_card %>
		<% @total_cash_revenue += @total_cash %>
	
		</tr>
	<% end %>
		</tbody>
	</table>
	</div>

	<legend>

	<!--Count expenses-->
	<% Expense.all.each do |expense| %>

	<% if session[:time_variable].present? %>
		<% if expense.date.strftime("%Y%m%d") == session[:time_variable].strftime("%Y%m%d") and
		expense.shift == "AM" %>
		<% @total_expense += expense.value %>

		<% end %>
	
	<% else %>

		<% if expense.date.strftime("%Y%m%d") == Date.today.strftime("%Y%m%d") and
		expense.shift == "AM" %>
		<% @total_expense += expense.value %>

		<% end %>
	
	<% end %>
	<% end %>


	Total Credit Card Payments: <%= @total_credit_card_revenue %> Euro<br>
	Total Cash Revenue: <%= @total_cash_revenue %><br>
	Total Expense: <%= @total_expense %><br>
	Total Revenue: <%= @total_rooms_revenue - @total_expense %> Euro
	</legend>

<!PM Shift> 

<h3>PM Shift</h3>
<div class="table-responsive">
<table class="table table-hover">
  <thead>
    <tr>
    
    		<th>Room</th>
    		<th>Total</th>
    		<th>Credit Card</th>
    		<th>Deposit</th>
      
     </tr>
  </thead>
  
<!--Initialize total revenues to zero. -->
<% @total_rooms_revenue = 0 %>
<% @total_credit_card_revenue = 0 %>
<% @total_cash_revenue = 0 %>
<% @total_expense = 0 %>

<!--Iterate through the room names, create variables room_total_ + room name (for example room_total_A, room_total_B etc)
to store the total revenue for the rooms individually.-->
<% room_names.each do |name| %>
	
	<tbody>
	<tr>
	<% @i = "room_total_" + name %>
	
	<!--Render the _count_Total page sending the rooms' name as room_variable_total, the rendered page will iterate through the
	Bed table and sum upp all the revenue in the particular rooms.-->
	<td><%= name %> Room</td>
	
	<%= @i = render partial: "count_Total", locals: {room_variable_total: name, time_variable: @time_variable,
	shift_variable: "PM"} %>
	
	<!--Sum up the particular revenues in @total_rooms_revenue variable without deposits-->
	<% @total_rooms_revenue += @total_price %>
	<% @total_credit_card_revenue += @total_credit_card %>
	<% @total_cash_revenue += @total_cash %>
	
	</tr>
<% end %>
	</tbody>
</table>
</div>

<!--Count expenses-->
	<% Expense.all.each do |expense| %>

	<% if session[:time_variable].present? %>
		<% if expense.date.strftime("%Y%m%d") == session[:time_variable].strftime("%Y%m%d") and
		expense.shift == "PM" %>
		<% @total_expense += expense.value %>

		<% end %>
	
	<% else %>

		<% if expense.date.strftime("%Y%m%d") == Date.today.strftime("%Y%m%d") and
		expense.shift == "PM" %>
		<% @total_expense += expense.value %>

		<% end %>
	
	<% end %>
	<% end %>

<legend>
Total Credit Card Payments: <%= @total_credit_card_revenue %> Euro<br>
Total Cash Revenue: <%= @total_cash_revenue %><br>
	Total Expense: <%= @total_expense %><br>
	Total Revenue: <%= @total_rooms_revenue - @total_expense %> Euro
</legend>

<!Night Shift>

<h3>NIGHT Shift</h3>
<div class="table-responsive">
<table class="table table-hover">
  <thead>
    <tr>
    
    		<th>Room</th>
    		<th>Total</th>
    		<th>Credit Card</th>
    		<th>Deposit</th>
      
     </tr>
  </thead>
<!--Initialize total revenues to zero. -->
<% @total_rooms_revenue = 0 %>
<% @total_credit_card_revenue = 0 %>
<% @total_cash_revenue = 0 %>
<% @total_expense = 0 %>

<!--Iterate through the room names, create variables room_total_ + room name (for example room_total_A, room_total_B etc)
to store the total revenue for the rooms individually.-->
<% room_names.each do |name| %>
	
	<tbody>
	<tr>
	<% @i = "room_total_" + name %>
	
	<!--Render the _count_Total page sending the rooms' name as room_variable_total, the rendered page will iterate through the
	Bed table and sum upp all the revenue in the particular rooms.-->
	<td><%= name %> Room</td>
	
	<%= @i = render partial: "count_Total", locals: {room_variable_total: name, time_variable: @time_variable,
	shift_variable: "NIGHT"} %>
	
	<!--Sum up the particular revenues in @total_rooms_revenue variable without deposits-->
	<% @total_rooms_revenue += @total_price %>
	<% @total_credit_card_revenue += @total_credit_card %>
	<% @total_cash_revenue += @total_cash %>
	
	</tr>
<% end %>
	</tbody>
</table>
</div>

<!--Count expenses-->
	<% Expense.all.each do |expense| %>

	<% if session[:time_variable].present? %>
		<% if expense.date.strftime("%Y%m%d") == session[:time_variable].strftime("%Y%m%d") and
		expense.shift == "NIGHT" %>
		<% @total_expense += expense.value %>

		<% end %>
	
	<% else %>

		<% if expense.date.strftime("%Y%m%d") == Date.today.strftime("%Y%m%d") and
		expense.shift == "NIGHT" %>
		<% @total_expense += expense.value %>

		<% end %>
	
	<% end %>
	<% end %>

<legend>
Total Credit Card Payments: <%= @total_credit_card_revenue %> Euro<br>
Total Cash Revenue: <%= @total_cash_revenue %><br>
	Total Expense: <%= @total_expense %><br> 
	Total Revenue: <%= @total_rooms_revenue - @total_expense %> Euro
</legend>

<!Day Total>

<h3>Day Total</h3>
<div class="table-responsive">
<table class="table table-hover">
  <thead>
    <tr>
    
    		<th>Room</th>
    		<th>Total</th>
    		<th>Credit Card</th>
    		<th>Deposit</th>
      
     </tr>
  </thead>
<!--Initialize total revenues to zero. -->
<% @total_rooms_revenue = 0 %>
<% @total_credit_card_revenue = 0 %>
<% @total_cash_revenue = 0 %>

<!--Iterate through the room names, create variables room_total_ + room name (for example room_total_A, room_total_B etc)
to store the total revenue for the rooms individually.-->
<% room_names.each do |name| %>
	
	<tbody>
	<tr>
	<% @i = "room_total_" + name %>
	
	<!--Render the _count_Total page sending the rooms' name as room_variable_total, the rendered page will iterate through the
	Bed table and sum upp all the revenue in the particular rooms.-->
	<td><%= name %> Room</td>
	
	<%= @i = render partial: "count_Total", locals: {room_variable_total: name, time_variable: @time_variable,
	} %>
	
	<!--Sum up the particular revenues in @total_rooms_revenue variable without deposits-->
	<% @total_rooms_revenue += @total_price %>
	<% @total_credit_card_revenue += @total_credit_card %>
	<% @total_cash_revenue += @total_cash %>
	
	</tr>
<% end %>
	</tbody>
</table>
</div>

<!--Count expenses-->
	<% Expense.all.each do |expense| %>

	<% if session[:time_variable].present? %>
		<% if expense.date.strftime("%Y%m%d") == session[:time_variable].strftime("%Y%m%d")%>
		<% @total_expense += expense.value %>

		<% end %>
	
	<% else %>

		<% if expense.date.strftime("%Y%m%d") == Date.today.strftime("%Y%m%d") %>
		<% @total_expense += expense.value %>

		<% end %>
	
	<% end %>
	<% end %>

<legend>
Total Credit Card Payments: <%= @total_credit_card_revenue %> Euro<br>
Total Cash Revenue: <%= @total_cash_revenue %><br>
	Total Expense: <%= @total_expense %><br>
	Total Revenue: <%= @total_rooms_revenue - @total_expense %> Euro
</legend>