config/routes.rb
Bobs::Application.routes.draw do
	
  resources :expenses

	get 'stats' => "admin#index"
	
	get 'login' => "sessions#new"
	post 'login' => "sessions#create"
	get 'logout' => "sessions#destroy"
  
	
  resources :users

  get "time/set"
  get "time/set_today"
  get "time/increase"
  get "time/decrease"

  resources :bookings

  resources :guests
	
  resources :beds

  root 'beds#index'

  get 'total' => 'beds#total'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bobs</title>
  
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse" role="navigation">
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      
      <div class="nav-collapse">
        <ul class="nav">
        <% if User.find_by_id(session[:user_id]).present? %>
        		<% user = User.find_by_id(session[:user_id]) %>
        		<li class="dropdown">
				    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= User.find_by_id(session[:user_id]).name %> <b class="caret"></b></a>
				    <ul class="dropdown-menu">
				      <li><%= link_to "Log Out", logout_url %></li>
				    		<% if user.name == "admin" %>
				    		
						    <li><%= link_to "Users", users_url %></li>
						   
				      
				      <% end %>
				    </ul>
      			</li>
      	 <% else %>
      	 	<a class="brand" href="#">Bobs</a>
      	 <% end %>
      	 
      	 <!-- If user is logged in, show menu -->
      	 <% if User.find_by_id(session[:user_id]).present? %>
      	 
      	 		<li><%= link_to 'Overview', beds_url %></li>
      	 		<li><%= link_to "Add Guest", new_guest_path %></li>
          <li><%= link_to 'Add Booking', new_booking_url %></li>
          <li><%= link_to "Add Expenses", new_expense_path %></li>
      	 		<li class="dropdown">
				    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= 'Lists'%><b class="caret"></b></a>
				    <ul class="dropdown-menu">
      	 				<li><%= link_to 'Guests', guests_url %></li>
				    		<li><%= link_to 'Bookings', bookings_url %></li>
				    		<li><%= link_to 'Expenses', expenses_url %></li>
				    		<li><%= link_to "Revenue", total_url %></li>
				    		<li><%= link_to "Stats", stats_url %></li>
				    </ul>
      			</li>

        </ul>
        
        
        
        <div style="float: right;" class="nav-collapse">
        <div class="nav-collapse">
        <ul class="nav">
        <li>
        <%= link_to "<", :controller => "time", :action => "decrease" %>
        </li>
        
        <li>
        <!--Check if date is manipulated (session time_variable is present), if yes,
        display the manipulated date, if not, show today's' date -->
		      <% if session[:time_variable].present? %>
		       	<%= link_to session[:time_variable].strftime("%Y %B %d, %A"), :controller => "time", :action => "set_today"  %>
					<% else %>
						<%= link_to Date.today.strftime("%Y %B %d, %A"), :controller => "time", :action => "set_today"  %>
		      <% end %>
        </li>
        
        <li>
        <%= link_to ">", :controller => "time", :action => "increase" %>
        <% end %>
        </li>
       
        </ul>
        </div>
      </div>
    </div>
  </div>
</div>
</nav>
<br>

<div class="main_division">
<%= yield %>
</div>

</body>
</html>